<?php

$this->load->view('header');
echo form_open("index.php/avaliacao/editar/".$avaliacao->professor->id);
echo MSG::getAlertMensagemClose(MSG::ALERT_SUCCESS, $this->session->flashdata('success'));
echo MSG::getAlertMensagemClose(MSG::ALERT_DANGER, validation_errors());
echo "<h2 class='form-signin-heading'>EDITAR AVALIAÇÃO</h2>";
echo "<div class='row'>";
echo "<div class='col-md-6'>";
echo "<div class='form-group'>";
echo form_label('Professor');
echo form_input(array('type' => 'text', 'class' => 'form-control', 'disabled' => true), set_value('',$avaliacao->professor->nome));
echo "</div>";
echo "</div>";
echo "<div class='col-md-3'>";
echo "<div class='form-group'>";
echo form_label('Pontualidade', 'pontualidade');
echo form_input(array('type' => 'number', 'id' => 'pontualidade', 'name' => 'pontualidade', 'class' => 'form-control', 'autofocus' => true), set_value('pontualidade',$avaliacao->pontualidade));
echo "</div>";
echo "</div>";
echo "<div class='col-md-3'>";
echo "<div class='form-group'>";
echo form_label('Assiduidade', 'assiduidade');
echo form_input(array('type' => 'number', 'id' => 'assiduidade', 'name' => 'assiduidade', 'class' => 'form-control'), set_value('assiduidade',$avaliacao->assiduidade));
echo "</div>";
echo "</div>";
echo "</div>";
echo "<div class='row'>";
echo "<div class='col-md-3'>";
echo "<div class='form-group'>";
echo form_label('Organização', 'organizacao');
echo form_input(array('type' => 'number', 'id' => 'organizacao', 'name' => 'organizacao', 'class' => 'form-control'), set_value('organizacao',$avaliacao->organizacao));
echo "</div>";
echo "</div>";
echo "<div class='col-md-3'>";
echo "<div class='form-group'>";
echo form_label('Disciplina', 'disciplina');
echo form_input(array('type' => 'number', 'id' => 'disciplina', 'name' => 'disciplina', 'class' => 'form-control'), set_value('disciplina',$avaliacao->disciplina));
echo "</div>";
echo "</div>";
echo "<div class='col-md-3'>";
echo "<div class='form-group'>";
echo form_label('Relacionamento', 'relacionamento');
echo form_input(array('type' => 'number', 'id' => 'relacionamento', 'name' => 'relacionamento', 'class' => 'form-control'), set_value('relacionamento',$avaliacao->relacionamento));
echo "</div>";
echo "</div>";
echo "<div class='col-md-3'>";
echo "<div class='form-group'>";
echo form_label('Metodologia', 'metodologia');
echo form_input(array('type' => 'number', 'id' => 'metodologia', 'name' => 'metodologia', 'class' => 'form-control'), set_value('metodologia',$avaliacao->metodologia));
echo "</div>";
echo "</div>";
echo "</div>";
echo "<div class='row'>";
echo "<div class='col-md-3'>";
echo "<div class='form-group'>";
echo form_label('Avaliação', 'avaliacao');
echo form_input(array('type' => 'number', 'id' => 'avaliacao', 'name' => 'avaliacao', 'class' => 'form-control'), set_value('avaliacao',$avaliacao->avaliacao));
echo "</div>";
echo "</div>";
echo "<div class='col-md-3'>";
echo "<div class='form-group'>";
echo form_label('Desenvolvimento Profissional', 'desenvolvimento');
echo form_input(array('type' => 'number', 'id' => 'desenvolvimento', 'name' => 'desenvolvimento', 'class' => 'form-control'), set_value('desenvolvimento',$avaliacao->desenvolvimento));
echo "</div>";
echo "</div>";
echo "<div class='col-md-3'>";
echo "<div class='form-group'>";
echo form_label('Compromisso Institucional', 'compromisso');
echo form_input(array('type' => 'number', 'id' => 'compromisso', 'name' => 'compromisso', 'class' => 'form-control'), set_value('compromisso',$avaliacao->compromisso));
echo "</div>";
echo "</div>";
echo "<div class='col-md-3'>";
echo "<div class='form-group'>";
echo form_label('Ética', 'etica');
echo form_input(array('type' => 'number', 'id' => 'etica', 'name' => 'etica', 'class' => 'form-control'), set_value('etica',$avaliacao->etica));
echo "</div>";
echo "</div>";
echo "</div>";
echo form_button(array("class" => "btn btn-primary", "content" => "ALTERAR", "type" => "submit"));
echo anchor('index.php/avaliacao/apagar/'.$avaliacao->professor->id, 'Apagar', array('class' => 'btn btn-danger pull-right'));
echo anchor('index.php/avaliacao/', 'Voltar', array('class' => 'btn btn-info'));
echo form_close();
$this->load->view('footer');
?>
